name: base_app
description: "Boilerplate base app for develop 22/dic/2024"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  go_router: ^14.6.2
  device_frame: ^1.2.0
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app-logo/xma.jpg"
  image_path_android: "assets/app-logo/xma.jpg"
  
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app-logo/xma.jpg"